bot.releases.enabled = true
package.versioned_files = [
  "apps/docs/package.json",
  "apps/web/package.json",
  "packages/eslint-config/package.json",
  "packages/typescript-config/package.json",
  "packages/ui/package.json",
]

[github]
owner = "sho918"
repo  = "knope-sample"
